### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "testpassword"
}

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Test User",
    "username": "testuser",
    "password": "testpassword",
    "email": "testuser@example.com"
}

### Rota protegida com token JWT
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNjc4MjFlNC05NDkyLTRmOWUtYTYyZS00ZWZlMWUzYmVlYzUiLCJlbWFpbCI6InRlc3R1c2VyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQ0NjgyOTExLCJleHAiOjE3NDUyODc3MTF9.NZFGmqAxOTXP7MV2rNh8XM-FRNfHxaYfopF6Pk73Bc4
