### Register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Alexandre Faria",
  "email": "Alexandre.faria@gmail.com",
  "password": "123456"
}

### Register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Penis Mole",
  "email": "PenisMole@gmail.com",
  "password": "123456"
}

### Login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "Alexandre.faria@gmail.com",
  "password": "123456"
}

### Register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Urien Silva",
  "email": "Urien.silva@gmail.com",
  "password": "123456"
}

### Login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "Urien.silva@gmail.com",
  "password": "123456"
}

### (Insira aqui o token do login abaixo para testes autenticados)
### Create Asset
POST http://localhost:3000/assets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhM2RmNTM0ZS1kY2UyLTRmM2YtYWIwMS0zYjM2NzMyZmY2MzciLCJlbWFpbCI6IlVyaWVuLnNpbHZhQGdtYWlsLmNvbSIsImlhdCI6MTc0NDczODU0MSwiZXhwIjoxNzQ0NzM4ODQxfQ.oUCvgusB--WvSSOUWP1GHYiOCLtomlemkAPnYBTCm9E
Content-Type: application/json

{
  "ticker": "PETR4"
}

### (Insira aqui o token do login abaixo para testes autenticados)
### Create Asset
POST http://localhost:3000/assets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NzhmNmYwZC03ZGI1LTRkOGEtYjU2Ni1jY2JmZWIyN2VjYzkiLCJlbWFpbCI6IkFsZXhhbmRyZS5mYXJpYUBnbWFpbC5jb20iLCJpYXQiOjE3NDQ3MzcyMTYsImV4cCI6MTc0NDczNzUxNn0.UisUdIPXYo88AYsBfNQltVuIlcylmnDtVCpKW-ruKvg
Content-Type: application/json

{
  "ticker": "GOGL4"
}

### List all Assets
GET http://localhost:3000/assets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NzhmNmYwZC03ZGI1LTRkOGEtYjU2Ni1jY2JmZWIyN2VjYzkiLCJlbWFpbCI6IkFsZXhhbmRyZS5mYXJpYUBnbWFpbC5jb20iLCJpYXQiOjE3NDQ3MzcyMTYsImV4cCI6MTc0NDczNzUxNn0.UisUdIPXYo88AYsBfNQltVuIlcylmnDtVCpKW-ruKvg

### Get Asset by ID
GET http://localhost:3000/assets/90a927be-73c5-44a7-aa63-f932b98c0e2d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NzhmNmYwZC03ZGI1LTRkOGEtYjU2Ni1jY2JmZWIyN2VjYzkiLCJlbWFpbCI6IkFsZXhhbmRyZS5mYXJpYUBnbWFpbC5jb20iLCJpYXQiOjE3NDQ3MzcyMTYsImV4cCI6MTc0NDczNzUxNn0.UisUdIPXYo88AYsBfNQltVuIlcylmnDtVCpKW-ruKvg

### Update Asset

### Overview do usuário (substitua o ID pelo real)
GET http://localhost:3000/users/a3df534e-dce2-4f3f-ab01-3b36732ff637/overview
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhM2RmNTM0ZS1kY2UyLTRmM2YtYWIwMS0zYjM2NzMyZmY2MzciLCJlbWFpbCI6IlVyaWVuLnNpbHZhQGdtYWlsLmNvbSIsImlhdCI6MTc0NDczODU0MSwiZXhwIjoxNzQ0NzM4ODQxfQ.oUCvgusB--WvSSOUWP1GHYiOCLtomlemkAPnYBTCm9E


### Test Brapi
GET https://brapi.dev/api/quote/PETR4?token=7L3BFUCcTMd8gvLKkFdRUi